# Obbligatori: Identificativi del progetto
sonar.organization=fdemusso
sonar.projectKey=fdemusso_BeechCMS

# Obbligatorio: Dove si trova il codice da analizzare (il punto indica la cartella corrente)
sonar.sources=.

# Fortemente consigliato: Cosa NON analizzare
# Se non escludi queste cartelle, SonarCloud analizzerà pacchetti esterni o file di test sballando le tue metriche
sonar.exclusions=**/node_modules/**, **/*.test.js, **/*.spec.js, **/dist/**, **/build/**

# Opzionale ma utile: Specifica la codifica
sonar.sourceEncoding=UTF-8