// SPDX-License-Identifier: MIT
// Copyright (c) 2024–2026 Flavio De Musso

/**
 * @module schema/emit
 * Renders a manifest as the source of a `beech.schema.ts` module — the inverse of the authoring DSL.
 *
 * The seed payload is embedded as the FROZEN canonical JSON literal (sprint 1's serializer), not as
 * a tree of `defineField.*` calls. Three reasons a future reader must not "improve" this:
 *  1. a call-tree emitter is a second serializer for the manifest shape, free to drift from
 *     `define.ts` the moment a branch type is added;
 *  2. the bytes here must match what `toCanonicalJson` produces, because that is what the validator
 *     and the diff compare — one format, one producer;
 *  3. a JSON object literal IS a valid TypeScript expression, so the emitted file typechecks in the
 *     consumer's project with zero extra machinery.
 *
 * A hand-authored manifest using the full DSL round-trips through this emitter unchanged in meaning:
 * `defineSchema`/`defineSeed`/`defineField` all erase to the same `BeechSchemaManifest`.
 */

import { canonicalStringify } from '../common/canonical-json.js'
import type { BeechSchemaManifest } from './manifest.types.js'

/** Header written at the top of every exported manifest. */
const HEADER =
  `// Generated by \`beech schema export\` from live D1 state.\n` +
  `//\n` +
  `// This file is DESIRED STATE, not runtime authority: the Worker never imports it and no deploy\n` +
  `// applies it. Edit it, review the diff in Git, then reconcile with \`beech schema plan\` /\n` +
  `// \`beech schema apply\`. Re-export at any time to refresh the snapshot.\n`

/**
 * Emits the full module source for a `beech.schema.ts`.
 *
 * Seeds are sorted by slug so two exports of the same database are byte-identical and a Git diff
 * shows schema change only. `version` is NOT passed to `defineSchema` — the DSL adds it, and an
 * excess property would fail the consumer's own typecheck.
 *
 * @throws CanonicalSerializationError when a seed carries a value that cannot survive a JSON
 * round-trip. That can only happen if a non-serializable value reached the `seeds` table, which is
 * a corrupt-state fault worth surfacing, not worth silently dropping.
 */
export function emitManifestModule(manifest: BeechSchemaManifest): string {
  const seeds = [...manifest.seeds].sort((a, b) => a.slug.localeCompare(b.slug))
  const literal = canonicalStringify({ seeds }).trimEnd()

  return (
    `${HEADER}\n` +
    `import { defineSchema } from '@beechcms/core/schema'\n\n` +
    `export default defineSchema(${literal})\n`
  )
}
