// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2024–2026 Flavio De Musso. All rights reserved.
// See LICENSE in the repository root for license terms.

/// <reference types="@cloudflare/workers-types" />
import { Hono } from 'hono'
import { cors } from 'hono/cors'
import { getCookie, setCookie, deleteCookie } from 'hono/cookie'
import type { Seed, ContentRepository, IdempotencyRepository, BeechBucket, MediaRepository, SystemStatsRepository, BeechHooks, JobRegistry } from '@beechcms/core'
import { sha256hex, SystemClock, SystemIdGenerator } from '@beechcms/core'
import type { Env, Variables, AppEnv } from './types'

export type { Env, Variables, AppEnv } from './types'
import { getClientIp } from './shared/utils/request-utils'

// Imports delle rotte e middleware
import { AUTH_ERRORS } from './auth/constants'
import {
  parseLoginBody,
  validateLoginInput,
  verifyPassword,
  DUMMY_PASSWORD_HASH,
} from './auth/utils/login-helpers'
import { generateRefreshToken } from './auth/utils/refresh-token'
import { authMiddleware } from './middleware/auth.middleware'
import contentFeature from './features/content'
import { widgetApp } from './features/widget/widget'
import { rotateFieldApp } from './features/rotate-field'
import { passwordResetApp } from './features/password-reset'
import { setupApp } from './features/setup'
import { draftApp } from './features/draft'
import { settingsApp } from './features/settings/settings.handler'
import { schemaApp } from './features/schema/schema.handler'
import { dashboardLayoutApp } from './features/dashboard-layout'
import { seedsApp } from './features/seeds'
import { notificationsApp } from './features/notifications'
import { automationsApp } from './features/automations/api/automations.handler'
import { statsApp } from './features/stats'
import { backrefsApp } from './features/backrefs'
import { webhooksApp } from './features/webhooks'
import { uploadRoutes, serveMediaHandler } from './features/upload'
import { publicRoutes } from './public/public-routes'
import { apiKeyMiddleware } from './public/api-key-middleware'
import { publicRateLimitMiddleware } from './public/rate-limit-middleware'
import { searchRouter } from "./features/search/search"
import type { ISeedRepository, IAutomationRepository, IAutomationRunner } from '@beechcms/core'
import { repositoryMiddleware } from './middleware/repository.middleware'
import { seedRegistryMiddleware } from './middleware/seed-registry.middleware'
import { storageMiddleware } from './middleware/storage.middleware'
import { InMemorySeedRepository } from './shared/db/repositories/in-memory-seed.repository'
import { authProvidersMiddleware } from './middleware/auth-providers.middleware'
import { rateLimiterMiddleware } from './middleware/rate-limit.middleware'
import { observabilityMiddleware } from './middleware/observability.middleware'
import { queueMiddleware } from './middleware/queue.middleware'

export interface BeechConfig {
  seeds: Seed[] | Record<string, Seed>
  repository?: ContentRepository
  idempotencyRepository?: IdempotencyRepository
  bucket?: BeechBucket
  mediaRepository?: MediaRepository
  systemStatsRepository?: SystemStatsRepository
  // Optional override: inject a custom ISeedRepository (e.g. InMemorySeedRepository for tests).
  // When omitted and seeds is non-empty, an InMemorySeedRepository is created automatically
  // for backward compatibility.
  seedRepository?: ISeedRepository
  automationRepository?: IAutomationRepository
  automationRunner?: IAutomationRunner
  /**
   * Programmatic lifecycle hooks (before/after create/update/delete), injected into
   * D1ContentRepository. They also run for writes generated by the AutomationRunner
   * (edit_field, create_entry), since both share the same repository instance —
   * be mindful of hook -> automation -> hook loops.
   */
  hooks?: BeechHooks
  /**
   * Registers developer-defined custom routes via pre-configured router instances,
   * without exposing Beech's internal middleware (authMiddleware, repositoryMiddleware, etc.).
   * `protectedRouter` has authMiddleware() applied automatically; `publicRouter` has none.
   */
  customRoutes?: (routers: { publicRouter: Hono<AppEnv>; protectedRouter: Hono<AppEnv> }) => void
  /**
   * Background job handlers, keyed by job name. Enqueue from custom routes via
   * `c.get('queue').enqueue(name, payload)`; consumed by the worker `queue()`
   * export. Handlers receive an engine-mediated JobContext — never raw D1.
   */
  jobs?: JobRegistry
}

// --- Costanti e helper ---
const REFRESH_TOKEN_EXPIRY_DAYS = 7
const SECONDS_PER_DAY = 24 * 60 * 60

function isRequestSecure(url: string): boolean {
  return new URL(url).protocol === 'https:'
}

function getRefreshTokenCookieOptions(secure: boolean) {
  return {
    httpOnly: true,
    secure,
    sameSite: 'Strict' as const,
    maxAge: REFRESH_TOKEN_EXPIRY_DAYS * SECONDS_PER_DAY,
    path: '/auth',
  }
}

function getRefreshTokenDeleteCookieOptions(secure: boolean) {
  return {
    httpOnly: true,
    secure,
    sameSite: 'Strict' as const,
    path: '/auth',
  }
}

function handleAuthError(context: any, error: unknown, operationName: string): Response {
  if (context.env.ENV !== 'production') {
    console.error(`${operationName} error:`, error)
  }
  return context.json({ error: AUTH_ERRORS.GENERIC_ERROR }, 500)
}

function extractPublicSeed(path: string): string {
  const match = path.match(/^\/api\/v1\/public\/([^/?]+)/)
  return match ? match[1] : ''
}

/**
 * Builds a fully configured Hono app. Seeds are hydrated from D1 at runtime via
 * seedRegistryMiddleware; config.seeds is retained for back-compat but no longer
 * drives request handling.
 */
export function createBeechApp(config: BeechConfig): Hono<{ Bindings: Env; Variables: Variables }> {
  // Back-compat shim: when callers (e.g. existing tests) pass seeds without a custom
  // seedRepository, wrap them in an InMemorySeedRepository so the middleware can serve
  // them without touching D1. Production index.ts passes seeds:[] so D1SeedRepository
  // is used as the live path.
  const seedsArray = Array.isArray(config.seeds) ? config.seeds : Object.values(config.seeds)
  const seedRepository = config.seedRepository
    ?? (seedsArray.length > 0 ? new InMemorySeedRepository(seedsArray) : undefined)

  const app = new Hono<{ Bindings: Env; Variables: Variables }>()

  // 1. Repository Injection (must be first — seedRegistryMiddleware depends on seedRepository)
  app.use('*', repositoryMiddleware({
    repository: config.repository,
    idempotencyRepository: config.idempotencyRepository,
    mediaRepository: config.mediaRepository,
    systemStatsRepository: config.systemStatsRepository,
    seedRepository,
    automationRepository: config.automationRepository,
    automationRunner: config.automationRunner,
    hooks: config.hooks,
  }))

  // 2. Seed Registry Hydration (D1-backed, version-token-cached per isolate)
  app.use('*', seedRegistryMiddleware())

  // 3. Storage / Auth / Rate Limiting / Observability
  app.use('*', storageMiddleware({
    bucket: config.bucket,
  }))

  app.use('*', queueMiddleware(config.jobs ?? {}))

  app.use('*', authProvidersMiddleware())
  app.use('*', rateLimiterMiddleware())
  app.use('*', observabilityMiddleware())

  app.use('*', async (context, next) => {
    const isDev = context.env.ENV !== 'production'

    return cors({
      origin: (origin) => {
        if (!origin) return origin ?? ''

        // In dev, allow all localhost/127.0.0.1 origins regardless of port
        if (isDev) {
          try {
            const { hostname } = new URL(origin)
            if (hostname === 'localhost' || hostname === '127.0.0.1') return origin
          } catch {}
        }

        const origins = (context.env.CORS_ORIGINS ?? 'http://localhost:5173')
          .split(',')
          .map((o) => o.trim())
          .filter(Boolean)

        if (origins.includes(origin)) return origin

        // Allow same-origin requests
        try {
          const originUrl = new URL(origin)
          const requestUrl = new URL(context.req.url)
          if (originUrl.protocol === requestUrl.protocol &&
              originUrl.hostname === requestUrl.hostname &&
              originUrl.port === requestUrl.port) {
            return origin
          }
        } catch {}

        return null
      },
      allowMethods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
      allowHeaders: ['Content-Type', 'Authorization', 'X-API-Key', 'Idempotency-Key'],
      credentials: true,
    })(context, next)
  })

  app.use('*', async (context, next) => {
    await next()
    if (context.req.path.startsWith('/admin')) return
    context.header('X-Frame-Options', 'DENY')
    context.header('X-Content-Type-Options', 'nosniff')
    context.header('Referrer-Policy', 'strict-origin-when-cross-origin')
    context.header('Permissions-Policy', 'geolocation=(), microphone=(), camera=()')
    context.header('Content-Security-Policy', "default-src 'self'; frame-ancestors 'none'")
  })

  // 2. Analytics Middleware
  app.use('/api/*', async (context, next) => {
    await next()
    if (context.req.method === 'OPTIONS') return
    if (context.res.status < 200 || context.res.status >= 300) return

    let executionCtx: any
    try { executionCtx = context.executionCtx } catch {}
    if (!executionCtx) return

    const analyticsRepository = context.get('analyticsRepository')
    if (!analyticsRepository) return

    const seedSlug = extractPublicSeed(context.req.path)

    executionCtx.waitUntil(
      analyticsRepository.recordRequest(seedSlug).catch((error: unknown) => {
        console.error('Analytics middleware error:', error)
      })
    )
  })

  // 3. Auth Routes
  app.post('/auth/login', async (context) => {
    try {
      let body: any
      try { body = await context.req.json() } catch { return context.json({ error: AUTH_ERRORS.INVALID_REQUEST }, 400) }
      const credentials = parseLoginBody(body)
      if (!credentials) return context.json({ error: AUTH_ERRORS.INVALID_REQUEST }, 400)
      const { email, password } = credentials
      if (!validateLoginInput(email, password)) return context.json({ error: AUTH_ERRORS.INVALID_REQUEST }, 400)

      const clientIp = getClientIp(context.req)
      const loginRateLimit = await context.get('rateLimiters').getLimiter('login').checkLimit(clientIp)
      if (!loginRateLimit.isAllowed) {
        const headers: Record<string, string> = {}
        if (loginRateLimit.retryAfterSeconds !== undefined) {
          headers['Retry-After'] = String(loginRateLimit.retryAfterSeconds)
        }
        return context.json({ error: AUTH_ERRORS.RATE_LIMIT_EXCEEDED }, 429, headers)
      }

      const user = await context.get('userRepository').findByEmail(email)
      const hashToCompare = user?.passwordHash ?? DUMMY_PASSWORD_HASH
      const isValid = await verifyPassword(password, hashToCompare, context.get('hashProvider'))

      if (!user || !isValid) return context.json({ error: AUTH_ERRORS.INVALID_CREDENTIALS }, 401)

      const accessToken = await context.get('tokenService').issue({ sub: user.id, email: user.email, name: user.name ?? undefined, surname: user.surname ?? undefined, role: user.role })
      const refreshToken = generateRefreshToken()
      const refreshTokenHash = await sha256hex(refreshToken)
      const nowSeconds = SystemClock.nowSeconds()

      await context.get('sessionRepository').saveRefreshToken({
        id: SystemIdGenerator.uuid(),
        userId: user.id,
        tokenHash: refreshTokenHash,
        expiresAt: nowSeconds + REFRESH_TOKEN_EXPIRY_DAYS * SECONDS_PER_DAY,
      })
      setCookie(context, 'refresh_token', refreshToken, getRefreshTokenCookieOptions(isRequestSecure(context.req.url)))
      return context.json({ token: accessToken, expiresIn: '15m' }, 200)
    } catch (error) {
      return handleAuthError(context, error, 'Login')
    }
  })

  app.post('/auth/refresh', async (context) => {
    try {
      const refreshClientIp = getClientIp(context.req)
      const refreshRateLimit = await context.get('rateLimiters').getLimiter('tokenRefresh').checkLimit(refreshClientIp)
      if (!refreshRateLimit.isAllowed) {
        const headers: Record<string, string> = {}
        if (refreshRateLimit.retryAfterSeconds !== undefined) {
          headers['Retry-After'] = String(refreshRateLimit.retryAfterSeconds)
        }
        return context.json({ error: AUTH_ERRORS.RATE_LIMIT_EXCEEDED }, 429, headers)
      }

      const refreshToken = getCookie(context, 'refresh_token')
      if (!refreshToken) return context.json({ error: 'Refresh token missing' }, 401)

      const nowSeconds = SystemClock.nowSeconds()
      const tokenHash = await sha256hex(refreshToken)
      const activeSession = await context.get('sessionRepository').findActiveByHash(tokenHash, nowSeconds)
      if (!activeSession) return context.json({ error: 'Invalid refresh token' }, 401)

      const user = await context.get('userRepository').findById(activeSession.userId)
      if (!user) {
        await context.get('sessionRepository').revokeByHash(tokenHash, nowSeconds)
        return context.json({ error: 'User not found' }, 401)
      }

      // Issue new tokens before revoking the old one: if saveRefreshToken fails,
      // the old token stays valid and the user is not locked out.
      const newAccessToken = await context.get('tokenService').issue({ sub: user.id, email: user.email, name: user.name ?? undefined, surname: user.surname ?? undefined, role: user.role })
      const newRefreshToken = generateRefreshToken()
      const newRefreshTokenHash = await sha256hex(newRefreshToken)

      await context.get('sessionRepository').saveRefreshToken({
        id: SystemIdGenerator.uuid(),
        userId: user.id,
        tokenHash: newRefreshTokenHash,
        expiresAt: nowSeconds + REFRESH_TOKEN_EXPIRY_DAYS * SECONDS_PER_DAY,
      })

      try {
        const revoked = await context.get('sessionRepository').revokeByHash(tokenHash, nowSeconds)
        if (!revoked) {
          await context.get('sessionRepository').revokeByHash(newRefreshTokenHash, nowSeconds)
          return context.json({ error: 'Invalid refresh token' }, 401)
        }

        setCookie(context, 'refresh_token', newRefreshToken, getRefreshTokenCookieOptions(isRequestSecure(context.req.url)))
        return context.json({ token: newAccessToken, expiresIn: '15m' }, 200)
      } catch (error) {
        await context.get('sessionRepository').revokeByHash(newRefreshTokenHash, nowSeconds).catch(() => {})
        throw error
      }
    } catch (error) {
      return handleAuthError(context, error, 'Refresh')
    }
  })

  app.post('/auth/logout', async (context) => {
    try {
      const refreshToken = getCookie(context, 'refresh_token')
      if (refreshToken) {
        const nowSeconds = SystemClock.nowSeconds()
        const tokenHash = await sha256hex(refreshToken)
        await context.get('sessionRepository').revokeByHash(tokenHash, nowSeconds)
      }
      deleteCookie(context, 'refresh_token', getRefreshTokenDeleteCookieOptions(isRequestSecure(context.req.url)))
      return context.json({ message: 'Logged out' }, 200)
    } catch (error) {
      return handleAuthError(context, error, 'Logout')
    }
  })

  // 4. Setup & Password Reset
  app.route('/', setupApp)
  app.route('/', passwordResetApp)

  // 5. Protected CMS API
  const apiProtected = new Hono<{ Bindings: Env; Variables: Variables }>()
  apiProtected.use('*', authMiddleware())

  apiProtected.route('/settings', settingsApp)
  apiProtected.route('/schema', schemaApp)
  apiProtected.route('/dashboard-layout', dashboardLayoutApp)
  apiProtected.route('/seeds', seedsApp)
  apiProtected.route('/content', notificationsApp)
  apiProtected.route('/content', statsApp)
  apiProtected.route('/content', rotateFieldApp)
  apiProtected.route('/content', draftApp)
  apiProtected.route('/content', backrefsApp)
  apiProtected.route('/content', contentFeature)
  apiProtected.route('/widget', widgetApp)
  apiProtected.route('/automations', automationsApp)
  apiProtected.route('/', uploadRoutes)
  
  // 6. Public API (must be registered before apiProtected to avoid auth middleware interception)
  const apiPublic = new Hono<{ Bindings: Env; Variables: Variables }>()
  apiPublic.use('*', publicRateLimitMiddleware())
  apiPublic.use('*', apiKeyMiddleware())
  apiPublic.route('/', publicRoutes)
  app.route('/api/v1/public', apiPublic)

  // Webhooks API (public, verified via signature)
  app.route('/api/webhooks', webhooksApp)

  app.get('/api/media/:key{.+}', (context) => serveMediaHandler(context))

  // Developer custom routes (must be mounted before apiProtected to avoid /api shadowing)
  if (config.customRoutes) {
    const publicRouter = new Hono<AppEnv>()
    const protectedRouter = new Hono<AppEnv>()

    protectedRouter.use('*', authMiddleware())

    config.customRoutes({ publicRouter, protectedRouter })

    app.route('/api/custom/public', publicRouter)
    app.route('/api/custom', protectedRouter)
  }

  app.route('/api', apiProtected)
  app.route('/api/search', searchRouter)

  // 7. Dashboard SPA — serve static assets from Workers Assets binding
  app.get('/admin', (context) => context.redirect('/admin/', 301))
  app.get('/admin/*', async (context) => {
    if (!context.env.ASSETS) {
      return context.text('Dashboard not configured. Set up the ASSETS binding in wrangler.toml pointing to node_modules/@beechcms/api/assets/dashboard', 503)
    }
    const url = new URL(context.req.url)
    const originalPath = url.pathname
    url.pathname = originalPath.replace(/^\/admin/, '') || '/'
    
    let assetResponse = await context.env.ASSETS.fetch(new Request(url.toString(), context.req.raw))
    if (assetResponse.status === 404) {
      // SPA fallback: any unmatched /admin/* route serves index.html
      assetResponse = await context.env.ASSETS.fetch(new Request(new URL('/index.html', context.req.url)))
    }
    // ASSETS returns an immutable Response — wrap it to inject security headers
    const headers = new Headers(assetResponse.headers)
    headers.set('Content-Security-Policy',
      "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; connect-src 'self'; frame-ancestors 'none'"
    )
    headers.set('X-Frame-Options', 'DENY')
    headers.set('X-Content-Type-Options', 'nosniff')
    headers.set('Referrer-Policy', 'strict-origin-when-cross-origin')
    return new Response(assetResponse.body, { status: assetResponse.status, headers })
  })

  return app
}
