// SPDX-License-Identifier: MIT
// Copyright (c) 2024–2026 Flavio De Musso

export { seedLoad } from './commands/seed-load.js'
export type { SeedLoadOptions } from './commands/seed-load.js'
export { init } from './commands/init.js'
export type { InitOptions } from './commands/init.js'
export { validate, validateSeeds } from './commands/validate.js'
export type { ValidateOptions, SeedValidationError } from './commands/validate.js'
export { seedCreate } from './commands/seed-create.js'
export type { SeedCreateOptions } from './commands/seed-create.js'
export { deploy } from './commands/deploy.js'
export type { DeployOptions } from './commands/deploy.js'
export { onboard } from './commands/onboard.js'
export type { OnboardOptions } from './commands/onboard.js'
export { update } from './commands/update.js'
export type { UpdateOptions } from './commands/update.js'
export { reset } from './commands/reset.js'
export type { ResetOptions } from './commands/reset.js'
export { generateTypes } from './commands/generate-types.js'
export type { GenerateTypesOptions } from './commands/generate-types.js'
export { schemaDiff } from './commands/schema-diff.js'
export type { SchemaDiffOptions } from './commands/schema-diff.js'

// New unified command mappings:
export { dbMigrate } from './commands/db-migrate.js'
export type { DbMigrateOptions } from './commands/db-migrate.js'
export { dbReset } from './commands/db-reset.js'
export type { DbResetOptions } from './commands/db-reset.js'
export { dev } from './commands/dev.js'
export type { DevOptions } from './commands/dev.js'
export { devStop } from './commands/dev-stop.js'
export { devReset } from './commands/dev-reset.js'
export { devTunnel } from './commands/dev-tunnel.js'
export { mailpitClear } from './commands/mailpit-clear.js'
export { logs } from './commands/logs.js'
export type { LogsOptions } from './commands/logs.js'
export { test } from './commands/test.js'
export type { TestOptions } from './commands/test.js'
export { lint } from './commands/lint.js'
export { doctor } from './commands/doctor.js'
export { forms } from './commands/forms.js'
export type { FormsOptions } from './commands/forms.js'
