// SPDX-License-Identifier: MIT
// Copyright (c) 2024–2026 Flavio De Musso

/**
 * HTTP client for communicating with the BeechCMS REST API from the MCP server.
 *
 * @remarks
 * Handles authentication via credentials (`BEECH_EMAIL` / `BEECH_PASSWORD`),
 * bearer token caching and automatic re-authentication upon HTTP 401 responses,
 * environment resolution (including local `.dev.vars` fallbacks), and RFC 7807 problem details parsing.
 *
 * @module
 */

import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * RFC 7807 Problem Details object structure returned by the BeechCMS API on HTTP error responses.
 */
export interface ProblemDetails {
  /** A URI reference that identifies the problem type. */
  type: string
  /** A short, human-readable summary of the problem type. */
  title: string
  /** The HTTP status code generated by the origin server. */
  status: number
  /** A human-readable explanation specific to this occurrence of the problem. */
  detail: string
}

/**
 * Error thrown by the BeechCMS MCP client when API requests, connection attempts, or authentication fail.
 */
export class BeechClientError extends Error {}

/**
 * Attempts to read the `BEECH_API_URL` setting from a local `.dev.vars` file in the current working directory.
 *
 * @returns The resolved URL string if found, otherwise `undefined`.
 */
function readDevVarsApiUrl(): string | undefined {
  const devVarsPath = join(process.cwd(), '.dev.vars')
  if (!existsSync(devVarsPath)) return undefined
  const contents = readFileSync(devVarsPath, 'utf8')
  const match = contents.match(/^BEECH_API_URL=(.*)$/m)
  return match ? match[1].trim() : undefined
}

/**
 * Configuration options resolved for connecting to the BeechCMS API.
 */
interface Config {
  /** The base URL of the BeechCMS API (e.g. `'http://localhost:8787'`). */
  baseUrl: string
  /** Email address for admin authentication. */
  email: string | undefined
  /** Password for admin authentication. */
  password: string | undefined
}

/**
 * Loads API connection configuration from environment variables, `.dev.vars`, or default fallback.
 *
 * @returns The resolved {@link Config} object.
 */
function loadConfig(): Config {
  return {
    baseUrl: process.env.BEECH_API_URL ?? readDevVarsApiUrl() ?? 'http://localhost:8787',
    email: process.env.BEECH_EMAIL,
    password: process.env.BEECH_PASSWORD,
  }
}

/** Active client configuration instance loaded at module evaluation time. */
const config = loadConfig()

/** Cached JWT bearer token obtained from a successful `/auth/login` request. */
let token: string | undefined

/**
 * Authenticates with BeechCMS using the configured admin email and password.
 *
 * @returns A promise that resolves to the acquired JWT bearer token string.
 * @throws {@link BeechClientError} If credentials are missing, the server cannot be reached, or authentication fails.
 */
async function login(): Promise<string> {
  if (!config.email || !config.password) {
    throw new BeechClientError(
      'Missing BEECH_EMAIL / BEECH_PASSWORD. Add them to the env block of your MCP client config (e.g. .mcp.json / claude_desktop_config.json).'
    )
  }
  let response: Response
  try {
    response = await fetch(`${config.baseUrl}/auth/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: config.email, password: config.password }),
    })
  } catch (error) {
    if (error instanceof TypeError || (error as NodeJS.ErrnoException)?.code === 'ECONNREFUSED') {
      throw new BeechClientError(`Cannot reach the BeechCMS API at ${config.baseUrl}. Start the local stack with: pnpm beech dev`)
    }
    throw error
  }
  if (!response.ok) {
    throw new BeechClientError(
      "Authentication failed. Check BEECH_EMAIL / BEECH_PASSWORD, and that the account has role 'admin'."
    )
  }
  const data = (await response.json()) as { token: string; expiresIn: string }
  token = data.token
  return token
}

/**
 * Executes a low-level fetch request to the BeechCMS API with standard headers and bearer token authorization.
 *
 * @param method - The HTTP method (e.g. `'GET'`, `'POST'`).
 * @param path - The API endpoint path (e.g. `'/api/seeds'`).
 * @param body - Optional request payload to be serialized as JSON.
 * @returns The raw fetch `Response` object.
 * @throws {@link BeechClientError} If the server is unreachable or connection is refused.
 */
async function rawFetch(method: string, path: string, body?: unknown): Promise<Response> {
  try {
    return await fetch(`${config.baseUrl}${path}`, {
      method,
      headers: {
        'Content-Type': 'application/json',
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
      },
      body: body !== undefined ? JSON.stringify(body) : undefined,
    })
  } catch (error) {
    if (error instanceof TypeError || (error as NodeJS.ErrnoException)?.code === 'ECONNREFUSED') {
      throw new BeechClientError(`Cannot reach the BeechCMS API at ${config.baseUrl}. Start the local stack with: pnpm beech dev`)
    }
    throw error
  }
}

/**
 * Generic response wrapper returned by {@link request}, containing the parsed JSON data and response headers.
 *
 * @typeParam T - The expected type of the response payload.
 */
export interface ApiResponse<T> {
  /** The parsed JSON response data. */
  data: T
  /** The response headers returned by the server. */
  headers: Headers
}

/**
 * Sends an authenticated HTTP request to the BeechCMS API endpoint.
 *
 * @remarks
 * - Automatically performs initial login if no token is cached.
 * - Handles token expiry by attempting a single re-login when receiving an HTTP 401.
 * - Parses RFC 7807 error responses into a descriptive {@link BeechClientError}.
 *
 * @typeParam T - Expected response payload type.
 * @param method - HTTP verb (e.g. `'GET'`, `'POST'`).
 * @param path - Target API route path relative to base URL (e.g. `'/api/seeds'`).
 * @param body - Optional payload to be JSON-serialized.
 * @returns A promise resolving to an {@link ApiResponse} containing typed data and headers.
 * @throws {@link BeechClientError} When authentication fails, the server is unreachable, or the request fails with a non-2xx status.
 */
export async function request<T = unknown>(method: string, path: string, body?: unknown): Promise<ApiResponse<T>> {
  if (!token) await login()

  let response = await rawFetch(method, path, body)

  if (response.status === 401) {
    await login()
    response = await rawFetch(method, path, body)
    if (response.status === 401) {
      throw new BeechClientError(
        "Authentication failed. Check BEECH_EMAIL / BEECH_PASSWORD, and that the account has role 'admin'."
      )
    }
  }

  if (!response.ok) {
    let problem: Partial<ProblemDetails> = {}
    try { problem = (await response.json()) as Partial<ProblemDetails> } catch { /* non-JSON error body */ }
    throw new BeechClientError(
      JSON.stringify({ status: problem.status ?? response.status, title: problem.title ?? response.statusText, detail: problem.detail ?? '' })
    )
  }

  const data = (await response.json()) as T
  return { data, headers: response.headers }
}
