// SPDX-License-Identifier: MIT
// Copyright (c) 2024–2026 Flavio De Musso

/**
 * HTTP client for communicating with the BeechCMS REST API from the MCP server.
 *
 * @remarks
 * Handles OAuth 2.1 authorization-code-with-PKCE authentication, on-disk token
 * caching with automatic refresh-and-retry upon HTTP 401 responses,
 * environment resolution (including local `.dev.vars` fallbacks), and RFC 7807 problem details parsing.
 *
 * @module
 */

import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import type { OAuthConfig } from './oauth.js'
import { authorize, refresh } from './oauth.js'
import { type CachedGrant, clearGrant, readGrant, writeGrant } from './token-store.js'

/**
 * RFC 7807 Problem Details object structure returned by the BeechCMS API on HTTP error responses.
 */
export interface ProblemDetails {
  /** A URI reference that identifies the problem type. */
  type: string
  /** A short, human-readable summary of the problem type. */
  title: string
  /** The HTTP status code generated by the origin server. */
  status: number
  /** A human-readable explanation specific to this occurrence of the problem. */
  detail: string
}

/**
 * Error thrown by the BeechCMS MCP client when API requests, connection attempts, or authentication fail.
 */
export class BeechClientError extends Error {}

/**
 * Attempts to read the `BEECH_API_URL` setting from a local `.dev.vars` file in the current working directory.
 *
 * @returns The resolved URL string if found, otherwise `undefined`.
 */
function readDevVarsApiUrl(): string | undefined {
  const devVarsPath = join(process.cwd(), '.dev.vars')
  if (!existsSync(devVarsPath)) return undefined
  const contents = readFileSync(devVarsPath, 'utf8')
  const match = contents.match(/^BEECH_API_URL=(.*)$/m)
  return match ? match[1].trim() : undefined
}

/** Seconds of clock skew treated as "already expired", so a token that dies
 *  in flight is refreshed before the request rather than after a 401. */
const EXPIRY_SKEW_MS = 30_000

/** Max retry attempts for transient 5xx responses (Workers/D1 cold starts). */
const MAX_TRANSIENT_RETRIES = 2

/** Base delay for the retry backoff; doubled per attempt plus jitter. */
const RETRY_BASE_DELAY_MS = 100

/** Statuses treated as transient and safe to retry unconditionally. */
function isRetryableStatus(status: number): boolean {
  return status === 502 || status === 503 || status === 504
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms))
}

/**
 * Resolved connection configuration. Credentials are gone: the only secrets
 * this process ever holds are OAuth tokens, in `~/.beechcms/mcp-tokens.json`.
 */
interface Config {
  baseUrl: string
  oauth: OAuthConfig
}

/**
 * Loads API connection and OAuth configuration from environment variables, `.dev.vars`, or defaults.
 *
 * @returns The resolved {@link Config} object.
 */
function loadConfig(): Config {
  const baseUrl = process.env.BEECH_API_URL ?? readDevVarsApiUrl() ?? 'http://localhost:8789'
  return {
    baseUrl,
    oauth: {
      apiUrl: baseUrl,
      authUrl: process.env.BEECH_AUTH_URL ?? baseUrl,
      clientId: process.env.BEECH_OAUTH_CLIENT_ID ?? 'beech-mcp',
      scope: process.env.BEECH_OAUTH_SCOPE ?? 'schema:read schema:write',
      timeoutMs: process.env.BEECH_OAUTH_TIMEOUT_MS ? Number(process.env.BEECH_OAUTH_TIMEOUT_MS) : 180_000,
    },
  }
}

/** Active client configuration instance loaded at module evaluation time. */
const config = loadConfig()

/** In-memory copy of the active grant. */
let grant: CachedGrant | undefined

/** Guards against two concurrent MCP tool calls opening two browser windows. */
let inFlightAuth: Promise<CachedGrant> | undefined

/**
 * Resolves a valid access token, transparently refreshing or launching the
 * browser authorization flow when the cached grant is missing or expired.
 *
 * @param forceRefresh - Bypass the expiry check and force a token refresh.
 * @returns A promise resolving to a valid bearer access token.
 */
async function getAccessToken(forceRefresh = false): Promise<string> {
  if (grant === undefined) {
    grant = readGrant(config.baseUrl, config.oauth.clientId)
  }

  if (grant && !forceRefresh && grant.expiresAt - Date.now() > EXPIRY_SKEW_MS) {
    return grant.accessToken
  }

  if (inFlightAuth) {
    const resolved = await inFlightAuth
    return resolved.accessToken
  }

  const authPromise = (async () => {
    if (grant?.refreshToken) {
      try {
        const refreshed = await refresh(config.oauth, grant.refreshToken)
        writeGrant(config.baseUrl, config.oauth.clientId, refreshed)
        grant = refreshed
        return refreshed
      } catch {
        clearGrant(config.baseUrl, config.oauth.clientId)
        grant = undefined
      }
    }

    const authorized = await authorize(config.oauth)
    writeGrant(config.baseUrl, config.oauth.clientId, authorized)
    grant = authorized
    return authorized
  })()

  inFlightAuth = authPromise
  try {
    const resolved = await authPromise
    return resolved.accessToken
  } finally {
    inFlightAuth = undefined
  }
}

/**
 * Executes a low-level fetch request to the BeechCMS API with standard headers and bearer token authorization.
 *
 * @param method - The HTTP method (e.g. `'GET'`, `'POST'`).
 * @param path - The API endpoint path (e.g. `'/api/seeds'`).
 * @param accessToken - The bearer token to authenticate the request with.
 * @param body - Optional request payload to be serialized as JSON.
 * @returns The raw fetch `Response` object.
 * @throws {@link BeechClientError} If the server is unreachable or connection is refused.
 */
async function rawFetch(method: string, path: string, accessToken: string, body?: unknown): Promise<Response> {
  try {
    return await fetch(`${config.baseUrl}${path}`, {
      method,
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${accessToken}`,
      },
      body: body !== undefined ? JSON.stringify(body) : undefined,
    })
  } catch (error) {
    if (error instanceof TypeError || (error as NodeJS.ErrnoException)?.code === 'ECONNREFUSED') {
      throw new BeechClientError(`Cannot reach the BeechCMS API at ${config.baseUrl}. Start the local stack with: pnpm beech dev`)
    }
    throw error
  }
}

/**
 * Generic response wrapper returned by {@link request}, containing the parsed JSON data and response headers.
 *
 * @typeParam T - The expected type of the response payload.
 */
export interface ApiResponse<T> {
  /** The parsed JSON response data. */
  data: T
  /** The response headers returned by the server. */
  headers: Headers
}

/**
 * Sends an authenticated HTTP request to the BeechCMS API endpoint.
 *
 * @remarks
 * - Resolves a cached, refreshed, or freshly-authorized OAuth access token before sending.
 * - Handles token expiry by attempting a single refresh-and-retry when receiving an HTTP 401.
 * - Surfaces a dedicated error when the token lacks a required scope (HTTP 403).
 * - Parses RFC 7807 error responses into a descriptive {@link BeechClientError}.
 *
 * @typeParam T - Expected response payload type.
 * @param method - HTTP verb (e.g. `'GET'`, `'POST'`).
 * @param path - Target API route path relative to base URL (e.g. `'/api/seeds'`).
 * @param body - Optional payload to be JSON-serialized.
 * @returns A promise resolving to an {@link ApiResponse} containing typed data and headers.
 * @throws {@link BeechClientError} When authentication fails, the server is unreachable, or the request fails with a non-2xx status.
 */
export async function request<T = unknown>(method: string, path: string, body?: unknown): Promise<ApiResponse<T>> {
  let accessToken = await getAccessToken()
  let response = await rawFetch(method, path, accessToken, body)

  if (response.status === 401) {
    accessToken = await getAccessToken(true)
    response = await rawFetch(method, path, accessToken, body)
    if (response.status === 401) {
      throw new BeechClientError(
        "Authorization failed. Run any Beech tool again to re-authorize in the browser, or revoke and re-grant the client from Settings → Connected apps."
      )
    }
  }

  for (let attempt = 0; isRetryableStatus(response.status) && attempt < MAX_TRANSIENT_RETRIES; attempt++) {
    await sleep(RETRY_BASE_DELAY_MS * 2 ** attempt + Math.random() * RETRY_BASE_DELAY_MS)
    response = await rawFetch(method, path, accessToken, body)
  }

  if (response.status === 403) {
    let body: { error?: string; error_description?: string } = {}
    try { body = (await response.json()) as { error?: string; error_description?: string } } catch { /* non-JSON error body */ }
    if (body.error === 'insufficient_scope') {
      const scope = body.error_description?.match(/'([^']+)'/)?.[1] ?? ''
      throw new BeechClientError(
        `Token lacks the '${scope}' scope. Revoke 'BeechCMS MCP Server' under Settings → Connected apps and re-authorize.`
      )
    }
    throw new BeechClientError(JSON.stringify({ status: 403, title: body.error ?? response.statusText, detail: body.error_description ?? '' }))
  }

  if (!response.ok) {
    let problem: Partial<ProblemDetails> = {}
    try { problem = (await response.json()) as Partial<ProblemDetails> } catch { /* non-JSON error body */ }
    throw new BeechClientError(
      JSON.stringify({ status: problem.status ?? response.status, title: problem.title ?? response.statusText, detail: problem.detail ?? '' })
    )
  }

  const data = (await response.json()) as T
  return { data, headers: response.headers }
}
