// SPDX-License-Identifier: MIT
// Copyright (c) 2024–2026 Flavio De Musso

/**
 * In-memory transient storage for schema migration plans generated by the BeechCMS MCP server.
 *
 * @remarks
 * BeechCMS schema mutations through MCP follow a two-step plan/apply workflow:
 * 1. An agent proposes a candidate schema modification via `beech_schema_plan`.
 * 2. The server computes DDL statements, safety classification, and stores the plan transiently with a 10-minute TTL.
 * 3. An agent applies the change via `beech_schema_apply`, consuming the plan single-use.
 *
 * @module
 */

/**
 * Representation of a pending schema migration plan stored in-memory.
 */
export interface StoredPlan {
  /** Unique UUID identifier assigned to the stored plan. */
  planId: string
  /** The target seed schema slug (e.g. `'posts'`, `'products'`). */
  slug: string
  /** The candidate seed definition proposed for schema modification. */
  candidate: unknown // Seed
  /** The schema version expected at the time this plan was generated, used for optimistic concurrency control. */
  expectedVersion: number
  /** Safety classification computed by the BeechCMS Botanical Engine: `'create'`, `'additive'`, or `'destructive'`. */
  classification: 'create' | 'additive' | 'destructive'
  /** Array of raw SQL DDL statements that would be executed to apply this plan. */
  statements: string[]
  /** Indicates whether a Full-Text Search (FTS) index rebuild is required after applying this schema change. */
  ftsRebuildNeeded: boolean
  /** Timestamp in milliseconds (`Date.now()`) when the plan was created and cached. */
  createdAt: number // Date.now()
}

/**
 * Time-to-live (TTL) duration in milliseconds for stored plans (strict 10-minute TTL: 600,000 ms).
 */
export const PLAN_TTL_MS = 10 * 60 * 1000 // strict 10-minute TTL

/** In-memory cache mapping unique plan IDs to stored plan records. */
const plans = new Map<string, StoredPlan>()

/**
 * Prunes expired plans from the in-memory map based on {@link PLAN_TTL_MS}.
 */
function sweepExpired(): void {
  const now = Date.now()
  for (const [id, plan] of plans) {
    if (now - plan.createdAt > PLAN_TTL_MS) plans.delete(id)
  }
}

/**
 * Saves a new candidate schema plan to in-memory transient storage with a generated UUID and current timestamp.
 *
 * @remarks
 * Automatically sweeps expired plans before inserting the new entry.
 *
 * @param plan - The plan payload excluding `planId` and `createdAt`.
 * @returns The newly stored plan record including its unique `planId` and creation timestamp.
 */
export function savePlan(plan: Omit<StoredPlan, 'planId' | 'createdAt'>): StoredPlan {
  sweepExpired()
  const stored: StoredPlan = { ...plan, planId: crypto.randomUUID(), createdAt: Date.now() }
  plans.set(stored.planId, stored)
  return stored
}

/**
 * Result returned when attempting to retrieve and consume a stored plan.
 *
 * @remarks
 * - `'ok'`: Plan was found, valid, and consumed.
 * - `'not_found'`: Plan ID does not exist or has already been consumed (single-use).
 * - `'expired'`: Plan exceeded its 10-minute TTL before consumption.
 */
export type TakePlanResult =
  | { status: 'ok'; plan: StoredPlan }
  | { status: 'not_found' }
  | { status: 'expired' }

/**
 * Retrieves and atomically consumes a stored plan by its unique ID (single-use).
 *
 * @remarks
 * Once retrieved, the plan is immediately deleted from storage regardless of whether
 * it has expired, guaranteeing single-use semantics.
 *
 * @param planId - The unique identifier of the stored plan to consume.
 * @returns A {@link TakePlanResult} object indicating `'ok'` with the plan, `'not_found'`, or `'expired'`.
 */
export function takePlan(planId: string): TakePlanResult {
  const plan = plans.get(planId)
  if (!plan) return { status: 'not_found' }
  plans.delete(planId)
  if (Date.now() - plan.createdAt > PLAN_TTL_MS) return { status: 'expired' }
  return { status: 'ok', plan }
}
