import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, '..');

const STAGES_DIR = path.join(ROOT_DIR, 'stages');
// Based on the filesystem, the folder is 01_sprint_planning
const ROADMAP_DIR = path.join(STAGES_DIR, '01_sprint_planning');
const MASTER_ROADMAP = path.join(ROADMAP_DIR, 'master_roadmap.md');
const SPRINT_OUTPUT_DIR = path.join(ROADMAP_DIR, 'output');

// Ensure output directories exist
if (!fs.existsSync(SPRINT_OUTPUT_DIR)) {
  fs.mkdirSync(SPRINT_OUTPUT_DIR, { recursive: true });
}

/**
 * Spawns an isolated Antigravity CLI agent session.
 * The session is automatically killed when the command exits, ensuring context is wiped.
 */
function runAgentSession(taskPrompt, model = 'Opus') {
  console.log(`\n[MASTER] Booting isolated agent session (Model: ${model})...`);
  
  // Replace linebreaks and quotes to safely pass as a single string argument.
  const safePrompt = taskPrompt.replace(/\n/g, ' ').replace(/"/g, '\\"');
  
  // Command relies on the `claude` CLI to execute a one-shot prompt.
  const cmd = `claude --dangerously-skip-permissions --model ${model} "${safePrompt}"`;
  
  try {
    // stdio: 'inherit' streams the agent's thoughts and tool usage in real-time.
    execSync(cmd, { stdio: 'inherit', cwd: ROOT_DIR });
  } catch (error) {
    console.error(`[MASTER] Agent session exited with an error:`, error.message);
    process.exit(1);
  }
  
  console.log(`[MASTER] Session killed (Context cleanly wiped).\n`);
}

// -----------------------------------------------------------------
// STAGE 1: Master Roadmap (Single Run)
// -----------------------------------------------------------------
console.log("=== STAGE 1: Generating Master Roadmap ===");

const MASTER_CONTEXT_PATH = path.join(ROADMAP_DIR, 'MASTER_CONTEXT.md');
const stage1Base = fs.readFileSync(MASTER_CONTEXT_PATH, 'utf-8');

const stage1Prompt = `${stage1Base}

---
CRITICAL RUNTIME INSTRUCTION:
Your ONLY task right now is to execute the instructions above.
Save your final output exactly to: ${MASTER_ROADMAP}
`;

// Boot first session
runAgentSession(stage1Prompt);

if (!fs.existsSync(MASTER_ROADMAP)) {
  console.error(`[MASTER] FATAL: ${MASTER_ROADMAP} was not generated.`);
  process.exit(1);
}

// -----------------------------------------------------------------
// STAGE 2: Sequential Worker Loop (Iterative Isolation)
// -----------------------------------------------------------------
console.log("=== STAGE 2: Sequential Worker Loop ===");

// Parse Master Roadmap to extract Sprints dynamically
const roadmapContent = fs.readFileSync(MASTER_ROADMAP, 'utf-8');
// Assuming standard Markdown "## Sprint 1", "## Sprint 2", etc.
const sprintRegex = /Sprint\s+\d+/gi;
const matchedSprints = [...new Set(roadmapContent.match(sprintRegex) || [])];

if (matchedSprints.length === 0) {
  console.error("[MASTER] FATAL: No Sprints found in the Master Roadmap.");
  process.exit(1);
}

console.log(`[MASTER] Detected Sprints to orchestrate: ${matchedSprints.join(', ')}`);

const WORKER_CONTEXT_PATH = path.join(ROADMAP_DIR, 'CONTEXT.md');
const stage2Base = fs.readFileSync(WORKER_CONTEXT_PATH, 'utf-8');

let previousSprintFile = null;

// Iterate sequentially to prevent cross-contamination
for (const sprintName of matchedSprints) {
  console.log(`\n--- Processing ${sprintName} ---`);
  
  const sprintSlug = sprintName.toLowerCase().replace(/\s+/g, '_'); // e.g. sprint_1
  const currentSprintFile = path.join(SPRINT_OUTPUT_DIR, `${sprintSlug}.md`);
  
  let stage2Prompt = `${stage2Base}

---
CRITICAL RUNTIME CONTEXT FOR THIS SPECIFIC WORKER:
- Target: You are exclusively planning **${sprintName}**.
- Master Roadmap: Reference ${MASTER_ROADMAP} to see your boundaries.
- Output File: You MUST save your final sprint plan exactly to **${currentSprintFile}**.
`;

  // Dynamically inject Reference Layer of the PREVIOUS sprint
  if (previousSprintFile && fs.existsSync(previousSprintFile)) {
    stage2Prompt += `- REFERENCE LAYER: You MUST read the previous sprint's output at **${previousSprintFile}** before planning, to ensure continuity and prevent duplicating work.\n`;
  }

  // Boot isolated session for this specific sprint
  runAgentSession(stage2Prompt);
  
  if (!fs.existsSync(currentSprintFile)) {
    console.error(`[MASTER] FATAL: ${currentSprintFile} was not generated by the agent.`);
    process.exit(1);
  }
  
  console.log(`[MASTER] ${sprintName} successfully planned and saved to ${currentSprintFile}.`);
  
  // Set current output as reference layer for the next iteration
  previousSprintFile = currentSprintFile;
}

console.log("\n=== Master Orchestration Complete ===");
