name: Semgrep Security Scan

on:
  pull_request:
    branches:
      - devs
      - master

jobs:
  semgrep-reviewdog:
    name: Controllo Sicurezza con Commenti
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Esegui Semgrep e annota la PR
        uses: reviewdog/action-semgrep@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          semgrep_rules: p/default
          reporter: github-pr-review
          level: error
