name: Semgrep Security Scan

on:
  pull_request:
    branches:
      - devs
      - master

jobs:
  semgrep-reviewdog:
    name: Scansione Sicurezza (commenti in PR)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Esegui Semgrep e annota la PR
        uses: g-wilson/action-semgrep@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          semgrep_config: p/default
          reporter: github-pr-review
          level: error
          filter_mode: diff_context
